vim.g.python3_host_prog = "~/.virtualenvs/neovim/bin/python3"

-- Auto-clear Neovim log files on startup
vim.fn.system("truncate -s 0 ~/.local/state/nvim/log ~/.local/state/nvim/lsp.log")

require("lazy_init")
require("core.autocommands")
require("core.options")
require("core.keymaps")
require("core.colourscheme")
require("plugins.aerial")
require("plugins.alpha")
require("plugins.autopairs")
require("plugins.autosave")
require("plugins.bufferline")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.competitest")
require("plugins.completion")
require("plugins.confirm-quit")
require("plugins.debugger")
require("plugins.dressing")
require("plugins.doge")
require("plugins.git")
require("plugins.motion")
require("plugins.impatient")
require("plugins.indentline")
require("plugins.lsp")
require("plugins.llm")
require("plugins.lspsaga")
require("plugins.lualine")
require("plugins.notify")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.project")
require("plugins.scrollbar")
require("plugins.surround")
require("plugins.telescope")
require("plugins.text-case")
require("plugins.toggleterm")
require("plugins.treesitter")
require("plugins.virtualenv")
require("plugins.whichkey")
require("plugins.zen_mode")
require("core.neovide")
